import type { Product, Testimonial } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'ZIUTY AirBeats 40H',
    image: 'https://m.media-amazon.com/images/I/71Jv0GewNeL._AC_SL1500_.jpg',
    benefits: ['Crystal-clear audio & deep bass', '40H playtime with ANC/ENC', 'Smart touch control', 'IPX7 waterproof for sports'],
    rating: 5,
    reviews: 289,
    affiliateLink: 'https://amzn.to/47uXgUt',
  },
  {
    id: 2,
    name: 'Cisily CleanZone Organizer',
    image: 'https://m.media-amazon.com/images/I/817NZ3rrbIL._AC_SX679_.jpg',
    benefits: ['Rustproof 304 stainless-steel', 'Holds sponge, soap, and brush', 'Stylish and space-saving', 'Keeps kitchen organized'],
    rating: 4,
    reviews: 176,
    affiliateLink: 'https://amzn.to/43ifjL7',
  },
  {
    id: 3,
    name: 'Owala ActiveFlow Bottle',
    image: 'https://m.media-amazon.com/images/I/410gXei0VaL._AC_SL1080_.jpg',
    benefits: ['Keeps drinks cold for hours', 'Double-wall insulation', 'Built-in straw & leak-proof design', 'Comfortable carry handle'],
    rating: 5,
    reviews: 491,
    affiliateLink: 'https://amzn.to/3XhcGpc',
  },
  {
    id: 4,
    name: 'Amazon Basics PowerGrip Dumbbells',
    image: 'https://m.media-amazon.com/images/I/81Y26toqdTL._AC_SL1500_.jpg',
    benefits: ['Neoprene coating for a secure grip', 'Hexagonal shape prevents rolling', 'Ideal for home workouts', 'Durable cast iron construction'],
    rating: 5,
    reviews: 832,
    affiliateLink: 'https://amzn.to/4hNPNmW',
  },
  {
    id: 5,
    name: 'CeraVe GlowRest Moisturizer',
    image: 'https://m.media-amazon.com/images/I/71r7bLsvaVL._SL1500_.jpg',
    benefits: ['Renews skin overnight', 'Nourishes with Niacinamide & Peptides', 'Hydrates with Hyaluronic Acid', 'Wake up to radiant skin'],
    rating: 5,
    reviews: 645,
    affiliateLink: 'https://amzn.to/3LN7hnf',
  },
  {
    id: 6,
    name: 'TrendPlain OilMaster Sprayer',
    image: 'https://m.media-amazon.com/images/I/71fHCOxxqXL._AC_SL1500_.jpg',
    benefits: ['2-in-1 glass bottle design', 'Precise spraying for healthier cooking', 'Ideal for oil, air fryers, salads', 'Durable and easy to use'],
    rating: 4,
    reviews: 211,
    affiliateLink: 'https://amzn.to/3JOumW8',
  },
  {
    id: 7,
    name: 'Kasa SmartControl Plug',
    image: 'https://m.media-amazon.com/images/I/51zoLDBO0wL._SL1105_.jpg',
    benefits: ['Control devices from anywhere', 'Works with Alexa & Google Home', 'No hub required', 'Easy, safe setup for a smart home'],
    rating: 5,
    reviews: 1024,
    affiliateLink: 'https://amzn.to/49BhgpK',
  },
  {
    id: 8,
    name: 'Kitsch GlowSculpt Gua Sha',
    image: 'https://m.media-amazon.com/images/I/71SMUQ9rvFL._AC_SL1500_.jpg',
    benefits: ['Lifts and contours the face', 'Helps reduce double chin', 'Improves lymphatic drainage', 'For a radiant, youthful look'],
    rating: 4,
    reviews: 350,
    affiliateLink: 'https://amzn.to/3LLzHxY',
  },
  {
    id: 9,
    name: 'MAX Houser SpaceSaver Shelf',
    image: 'https://m.media-amazon.com/images/I/612rBzPL0FL._AC_SL1500_.jpg',
    benefits: ['Maximizes closet space', '6-tier foldable design', 'Easy to hang with 2 sturdy hooks', 'Organizes clothes, shoes, accessories'],
    rating: 4,
    reviews: 198,
    affiliateLink: 'https://amzn.to/4oPrhEe',
  },
  {
    id: 10,
    name: 'Amazon Smart Plug – Works with Alexa',
    image: 'https://m.media-amazon.com/images/I/711nxnsm6nL._AC_SL1500_.jpg',
    benefits: ['Adds voice control to any outlet', 'Works seamlessly with Alexa', 'Certified for Humans – struggle-free setup', 'No smart home hub required'],
    rating: 5,
    reviews: 1540,
    affiliateLink: 'https://amzn.to/4hJEmfS',
  },
  {
    id: 11,
    name: 'Soundcore by Anker P20i True Wireless Earbuds',
    image: 'https://m.media-amazon.com/images/I/51+qzpA7y+L._AC_SL1341_.jpg',
    benefits: ['30H total playtime', 'Big bass from 10mm drivers', 'Bluetooth 5.3 connectivity', 'AI-enhanced clear calls'],
    rating: 5,
    reviews: 987,
    affiliateLink: 'https://amzn.to/491oHGy',
  },
  {
    id: 12,
    name: 'Amazon Echo Dot (5th Gen)',
    image: 'https://m.media-amazon.com/images/I/71yRY8YlAbL._AC_SL1500_.jpg',
    benefits: ['Our best-sounding Echo Dot yet', 'Control music and smart home with your voice', 'Built-in Alexa assistant', 'Compact and stylish design'],
    rating: 5,
    reviews: 2100,
    affiliateLink: 'https://amzn.to/43Rs8fl',
  },
  {
    id: 13,
    name: 'Fire TV Stick 4K Max',
    image: 'https://m.media-amazon.com/images/I/61ZYTXa9DdL._AC_SL1000_.jpg',
    benefits: ['Powerful 4K streaming', 'Supports next-gen Wi-Fi 6', 'Dolby Vision/HDR10+ for cinematic viewing', 'Includes Alexa Voice Remote'],
    rating: 5,
    reviews: 1850,
    affiliateLink: 'https://amzn.to/4osRKrj',
  },
  {
    id: 14,
    name: 'Instant Pot Duo 7‑in‑1 Multicooker',
    image: 'https://m.media-amazon.com/images/I/71xbdrK1vOL._AC_SL1500_.jpg',
    benefits: ['7-in-1 multifunctional cooker', 'Saves time and kitchen space', 'Quick cooking, steaming, and roasting', 'Easy to use and clean'],
    rating: 5,
    reviews: 3500,
    affiliateLink: 'https://amzn.to/47DwPMt',
  },
  {
    id: 15,
    name: 'Ninja Air Fryer AF101',
    image: 'https://m.media-amazon.com/images/I/71+8uTMDRFL._AC_SL1500_.jpg',
    benefits: ['Quick and healthy air frying', 'Crispy results with up to 75% less fat', 'Compact size for easy storage', '4-quart capacity'],
    rating: 5,
    reviews: 2900,
    affiliateLink: 'https://amzn.to/4qGS2fH',
  },
  {
    id: 16,
    name: 'Anker NEBULA Capsule Smart Mini Projector',
    image: 'https://m.media-amazon.com/images/I/610dDc+YfDL._AC_SL1500_.jpg',
    benefits: ['Smart portable mini projector', 'Pocket-sized for entertainment anywhere', 'Up to 100-inch picture', '360° omnidirectional speaker'],
    rating: 4,
    reviews: 890,
    affiliateLink: 'https://amzn.to/493dhlH',
  },
  {
    id: 17,
    name: 'ThermoPro TP17 Dual Probe Digital Meat Thermometer',
    image: 'https://m.media-amazon.com/images/I/81vguXyMCmL._AC_SL1500_.jpg',
    benefits: ['Dual probes for accurate temperature monitoring', 'Ideal for grilling, smoking, and oven', 'Backlit LCD for easy reading', 'Fast and precise readings'],
    rating: 5,
    reviews: 1200,
    affiliateLink: 'https://amzn.to/4qMu3f3',
  },
  {
    id: 18,
    name: 'Fitbit Inspire 2 Health & Fitness Tracker',
    image: 'https://m.media-amazon.com/images/I/51uHD-x+3-L._AC_SL1500_.jpg',
    benefits: ['24/7 heart rate tracking', 'Tracks activity, steps, and sleep', 'Up to 10 days of battery life', 'Includes 1-year Fitbit Premium trial'],
    rating: 4,
    reviews: 1450,
    affiliateLink: 'https://amzn.to/4oSS1Ub',
  },
  {
    id: 19,
    name: 'ThickBoost Set',
    image: 'https://m.media-amazon.com/images/I/71cmialeElL._SL1500_.jpg',
    benefits: ['Anti-thinning shampoo & conditioner', 'Infused with Biotin & DHT blockers', 'Promotes healthier, fuller-looking hair', 'Color-safe for men and women'],
    rating: 4,
    reviews: 550,
    affiliateLink: 'https://amzn.to/47H5zeC',
  }
];

export const TESTIMONIALS: Testimonial[] = [
    {
        id: 1,
        quote: "The ZIUTY earbuds are a game-changer for my workouts. Incredible sound and they stay put. A must-buy!",
        author: 'Mike T.',
        location: 'Chicago, IL',
        rating: 5,
    },
    {
        id: 2,
        quote: "My kitchen sink has never been so organized, thanks to the Cisily organizer. It's stylish and super functional.",
        author: 'Emily S.',
        location: 'Miami, FL',
        rating: 5,
    },
    {
        id: 3,
        quote: "I'm obsessed with my Owala bottle! It keeps my water ice-cold all day and the built-in straw is so convenient.",
        author: 'Chloe B.',
        location: 'Los Angeles, CA',
        rating: 5,
    }
];
